name: Talking Points
favicon: null
layout_spectrum: 0.51833
typography_spectrum: 0.51209
title: Talking Points with Joshua Gadsby
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0a0a0a'
    - '#b7b09d'
    - '#87827c'
    - '#344966'
  brandStrength: 1
  lightness: 0.9127966954838485
  saturation: 1
  rhythmicContrast: 1
purpose: []
